version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Installing dependencies...
      - dotnet restore
  build:
    commands:
      - echo Building the project...
      - dotnet build --configuration Release
      - dotnet publish -c Release -o ./publish_output
artifacts:
  files:
    - '**/*'
  base-directory: ./publish_output
